### ISSUE TITLE
Traceback when player logs in due to missing settings.CHANNEL_CONNECTINFO

### ISSUE THREAD

**Issue by titeuf87** [evennia/evennia#1177]
#### Brief summary of issue / Description of requested feature:
With the latest commits, when loggin in I get the following traceback on the terminal:
```
2017-01-27T18:00:12+0000 [AMPProtocol,0,127.0.0.1] [::] Traceback (most recent call last):
2017-01-27T18:00:12+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/home/arch/Projects/evenniagame/evennia/evennia/server/serversession.py", line 309, in log
2017-01-27T18:00:12+0000 [AMPProtocol,0,127.0.0.1] [::]     cchan = settings.CHANNEL_CONNECTINFO
2017-01-27T18:00:12+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/home/arch/Projects/evenniagame/venv/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
2017-01-27T18:00:12+0000 [AMPProtocol,0,127.0.0.1] [::]     return getattr(self._wrapped, name)
2017-01-27T18:00:12+0000 [AMPProtocol,0,127.0.0.1] [::] AttributeError: 'Settings' object has no attribute 'CHANNEL_CONNECTINFO'
```

For the rest, nothing bad happens.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Log into your Evennia game
2. Look at the terminal

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
This traceback got introduced with commit c6d9c0619e1584181c281e16c6785b51a99e0eed
The exception always happened, even before that commit, but it never displayed because before that it was just swallowed in a try...except.
