### PR TITLE
upgrade to 1.0: instruct how to fix deprecation errors

### PR DESCRIPTION
**Pull request by aogier**
#### Brief overview of PR changes/additions

When upgrading from 0.9.5 to 1.0 django errors out because a deprecation in urlpatterns utils. This PR gives instructions on how to fix the error that would come up in eg. `evennia migrate`:

```
  File "/home/oggei/dev/evennia/zero-dot/web/urls.py", line 7, in <module>
    from django.conf.urls import url, include
ImportError: cannot import name 'url' from 'django.conf.urls' (/home/oggei/.pyenv/versions/3.9.13/envs/evennia/lib/python3.9/site-packages/django/conf/urls/__init__.py)
```

HTH, regards

### CODE REVIEW

**Comment by aogier** [comment]
e poi suca, coglione :D
