### ISSUE TITLE
[BUG] Compilation error in characters.py causes character duplication glitch

### ISSUE THREAD

**Issue by mrseeker** [evennia/evennia#2438]
#### Describe the bug
When characters.py contains an error and fails, a duplication glitch occurs where the superuser character is constantly being recreated, causing it to crash the server due to resource exhaustion. Shutting down the server and stopping the batch processes does not prevent stopping this behaviour, a manual kill of the offending process is needed to shut it down.

#### To Reproduce
1. Create a new game
2. Change the file at Typeclasses -> Characters.py, and add the following code as an example to cause an error:
```
def at_object_creation(self):
    tickerhandler.add(interval=6, callback=self.at_turn_start)
```
3. Do an evennia migrate
4. Create a superuser
5. Start evennia
6. The server will now boot and create user 1, followed by duplicating user 1 until it runs out of disk space.
7. Check how many accounts exist using the web interface.

#### Expected behavior
An error saying that user 1 could not be created due to compilation errors during creation of the superuser.

#### Environment, Evennia version, OS etc
Evennia 1.0-dev (rev f5581ba84) (rev f5581ba84)
    OS: Windows 10
    Python: 3.9.5
    Twisted: 21.2.0
    Django: 3.2.4

#### Additional context
Stopping evennia (using evennia stop) won't work, a rogue python shell is still running in the background, locking the database.
