### ISSUE TITLE
Copying an object with tags returns an error. Possible fix included.

### ISSUE THREAD

**Issue by FatherGrishnak** [evennia/evennia#1909]
#### Brief summary of issue / Description of requested feature:
copy_object on line 510 of evennia/objects/manager.py throws an error when used: 
"AttributeError: 'Tag' object has no attribute 'key'"

#### Steps to reproduce the issue / Reasons for adding feature:

1. create an object "original_object".
2. Add tags to "original_object"
3. newobject = ObjectDB.objects.copy_object(original_object)
4. "AttributeError: 'Tag' object has no attribute 'key' "

#### Error output / Expected result of feature
AttributeError: 'Tag' object has no attribute 'key' 

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Using latest 0.9.0 master
The file is  evennia/objects/manager.py

My fix: replace "tag.key" etc in line 510 as below

            new_object.tags.add(tag=tag.db_key, category=tag.db_category, data=tag.db_data)

With this edit to evennia/objects/manager.py, my project now compiles, and functions as expected. I can't promise this is the best fix, and would dearly like someone more experienced than myself to check.

I have been away from Evennia for a while, but that code on line 510 worked perfectly in 0.8.0. (prior to 0.8.0 tags were not copied at all). Did the changes in 0.9.0 change the names of the tag attributes?

**Comment by Griatch** [comment]
Hm, the Tag model have no wrappers to rename its `db_*` fields, and this code has not changed in 5 years. So `Tag.key` should never have worked, really :smile: I'll look it over and make the change you suggest, that sounds like the correct thing to do.

**Comment by FatherGrishnak** [comment]
:thumbsup:

Thank you, Griatch

**Comment by Griatch** [comment]
It's not fixed yet, so don't close it. :)
